// Generated by CoffeeScript 1.9.1
(function() {
  var cl, mysql, mysqlDB;

  cl = console.log;

  mysql = require('mysql');

  mysqlDB = mysql.createConnection({
    host: '152.99.170.178',
    port: '3306',
    user: 'root',
    password: 'happy$700*pc',
    database: 'RFC3'
  });

  mysqlDB.connect(function(err) {
    return cl((err != null ? err.message : void 0) || 'success');
  });

  mysqlDB.query('select 1 from dual;', function(err, rows, fields) {
    return cl(err || rows);
  });

  mysqlDB.end();

}).call(this);
